import { BaseTimetable } from '../types/subject';

// Helper to create a day schedule
const createSchedule = (data: Record<string, Record<number, { code: string; name: string; type: 'core' | 'elective' | 'break' }>>) => data;

export const BASE_TIMETABLES: Record<string, BaseTimetable> = {
    // ม.1
    'M1': {
        id: 'M1', label: 'ม.1', grade: 1,
        schedule: createSchedule({
            Monday: { 0: { code: 'ว21101', name: 'วิทย์', type: 'core' }, 1: { code: 'ค21101', name: 'คณิต', type: 'core' }, 2: { code: 'ท21101', name: 'ไทย', type: 'core' }, 3: { code: 'ส21101', name: 'สังคม', type: 'core' }, 4: { code: 'อ21101', name: 'อังกฤษ', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'พ21101', name: 'พละ', type: 'core' }, 9: { code: 'ศ21101', name: 'ศิลปะ', type: 'core' } },
            Tuesday: { 0: { code: 'อ21101', name: 'อังกฤษ', type: 'core' }, 1: { code: 'ค21101', name: 'คณิต', type: 'core' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'ว21101', name: 'วิทย์', type: 'core' }, 4: { code: 'ท21101', name: 'ไทย', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 7: { code: 'ส21101', name: 'สังคม', type: 'core' }, 8: { code: 'ก21101', name: 'กิจกรรม', type: 'core' } },
            Wednesday: { 0: { code: 'ว21101', name: 'วิทย์', type: 'core' }, 1: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'ค21101', name: 'คณิต', type: 'core' }, 4: { code: 'อ21101', name: 'อังกฤษ', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ท21101', name: 'ไทย', type: 'core' }, 7: { code: 'ศ21101', name: 'ศิลปะ', type: 'core' }, 8: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' } },
            Thursday: { 0: { code: 'ค21101', name: 'คณิต', type: 'core' }, 1: { code: 'ท21101', name: 'ไทย', type: 'core' }, 2: { code: 'อ21101', name: 'อังกฤษ', type: 'core' }, 3: { code: 'ว21101', name: 'วิทย์', type: 'core' }, 4: { code: 'ส21101', name: 'สังคม', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'พ21101', name: 'พละ', type: 'core' } },
            Friday: { 0: { code: 'ว21101', name: 'วิทย์', type: 'core' }, 1: { code: 'ส21101', name: 'สังคม', type: 'core' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'ค21101', name: 'คณิต', type: 'core' }, 4: { code: 'ท21101', name: 'ไทย', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ก21101', name: 'กิจกรรม', type: 'core' }, 7: { code: 'ก21101', name: 'กิจกรรม', type: 'core' } }
        })
    },
    // ม.2-3 same structure as M1
    'M2': {
        id: 'M2', label: 'ม.2', grade: 2, schedule: createSchedule({
            Monday: { 0: { code: 'ว22101', name: 'วิทย์', type: 'core' }, 1: { code: 'ค22101', name: 'คณิต', type: 'core' }, 2: { code: 'ท22101', name: 'ไทย', type: 'core' }, 3: { code: 'ส22101', name: 'สังคม', type: 'core' }, 4: { code: 'อ22101', name: 'อังกฤษ', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'พ22101', name: 'พละ', type: 'core' } },
            Tuesday: { 0: { code: 'อ22101', name: 'อังกฤษ', type: 'core' }, 1: { code: 'ค22101', name: 'คณิต', type: 'core' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'ว22101', name: 'วิทย์', type: 'core' }, 4: { code: 'ท22101', name: 'ไทย', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 7: { code: 'ส22101', name: 'สังคม', type: 'core' }, 8: { code: 'ศ22101', name: 'ศิลปะ', type: 'core' } },
            Wednesday: { 0: { code: 'ว22101', name: 'วิทย์', type: 'core' }, 1: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'ค22101', name: 'คณิต', type: 'core' }, 4: { code: 'อ22101', name: 'อังกฤษ', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ท22101', name: 'ไทย', type: 'core' }, 7: { code: 'ศ22101', name: 'ศิลปะ', type: 'core' }, 8: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' } },
            Thursday: { 0: { code: 'ค22101', name: 'คณิต', type: 'core' }, 1: { code: 'ท22101', name: 'ไทย', type: 'core' }, 2: { code: 'อ22101', name: 'อังกฤษ', type: 'core' }, 3: { code: 'ว22101', name: 'วิทย์', type: 'core' }, 4: { code: 'ส22101', name: 'สังคม', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'พ22101', name: 'พละ', type: 'core' } },
            Friday: { 0: { code: 'ว22101', name: 'วิทย์', type: 'core' }, 1: { code: 'ส22101', name: 'สังคม', type: 'core' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'ค22101', name: 'คณิต', type: 'core' }, 4: { code: 'ท22101', name: 'ไทย', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ก22101', name: 'กิจกรรม', type: 'core' }, 7: { code: 'ก22101', name: 'กิจกรรม', type: 'core' } }
        })
    },
    'M3': {
        id: 'M3', label: 'ม.3', grade: 3, schedule: createSchedule({
            Monday: { 0: { code: 'ว23101', name: 'วิทย์', type: 'core' }, 1: { code: 'ค23101', name: 'คณิต', type: 'core' }, 2: { code: 'ท23101', name: 'ไทย', type: 'core' }, 3: { code: 'ส23101', name: 'สังคม', type: 'core' }, 4: { code: 'อ23101', name: 'อังกฤษ', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'พ23101', name: 'พละ', type: 'core' } },
            Tuesday: { 0: { code: 'อ23101', name: 'อังกฤษ', type: 'core' }, 1: { code: 'ค23101', name: 'คณิต', type: 'core' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'ว23101', name: 'วิทย์', type: 'core' }, 4: { code: 'ท23101', name: 'ไทย', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 7: { code: 'ส23101', name: 'สังคม', type: 'core' }, 8: { code: 'ศ23101', name: 'ศิลปะ', type: 'core' } },
            Wednesday: { 0: { code: 'ว23101', name: 'วิทย์', type: 'core' }, 1: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'ค23101', name: 'คณิต', type: 'core' }, 4: { code: 'อ23101', name: 'อังกฤษ', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ท23101', name: 'ไทย', type: 'core' }, 7: { code: 'ศ23101', name: 'ศิลปะ', type: 'core' }, 8: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' } },
            Thursday: { 0: { code: 'ค23101', name: 'คณิต', type: 'core' }, 1: { code: 'ท23101', name: 'ไทย', type: 'core' }, 2: { code: 'อ23101', name: 'อังกฤษ', type: 'core' }, 3: { code: 'ว23101', name: 'วิทย์', type: 'core' }, 4: { code: 'ส23101', name: 'สังคม', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'พ23101', name: 'พละ', type: 'core' } },
            Friday: { 0: { code: 'ว23101', name: 'วิทย์', type: 'core' }, 1: { code: 'ส23101', name: 'สังคม', type: 'core' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'ค23101', name: 'คณิต', type: 'core' }, 4: { code: 'ท23101', name: 'ไทย', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ก23101', name: 'กิจกรรม', type: 'core' }, 7: { code: 'ก23101', name: 'กิจกรรม', type: 'core' } }
        })
    },
    // ม.4 วิทย์-คณิต
    'M4-Science': {
        id: 'M4-Science', label: 'ม.4 วิทย์-คณิต', grade: 4, schedule: createSchedule({
            Monday: { 0: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 1: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 2: { code: 'ว30101', name: 'ฟิสิกส์', type: 'core' }, 3: { code: 'ค30101', name: 'คณิต', type: 'core' }, 4: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ว30102', name: 'เคมี', type: 'core' }, 7: { code: 'ท30101', name: 'ไทย', type: 'core' }, 8: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 9: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' } },
            Tuesday: { 0: { code: 'ท30101', name: 'ไทย', type: 'core' }, 1: { code: 'ว30102', name: 'เคมี', type: 'core' }, 2: { code: 'ว30103', name: 'ชีวะ', type: 'core' }, 3: { code: 'ค30101', name: 'คณิต', type: 'core' }, 4: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 7: { code: 'ว30101', name: 'ฟิสิกส์', type: 'core' }, 8: { code: 'ส30101', name: 'สังคม', type: 'core' } },
            Wednesday: { 0: { code: 'ว30101', name: 'ฟิสิกส์', type: 'core' }, 1: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'ว30103', name: 'ชีวะ', type: 'core' }, 4: { code: 'ค30101', name: 'คณิต', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ส30101', name: 'สังคม', type: 'core' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'อ30101', name: 'อังกฤษ', type: 'core' } },
            Thursday: { 0: { code: 'ค30101', name: 'คณิต', type: 'core' }, 1: { code: 'ว30102', name: 'เคมี', type: 'core' }, 2: { code: 'ท30101', name: 'ไทย', type: 'core' }, 3: { code: 'ว30101', name: 'ฟิสิกส์', type: 'core' }, 4: { code: 'ว30103', name: 'ชีวะ', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'พ30101', name: 'พละ', type: 'core' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' } },
            Friday: { 0: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 1: { code: 'ค30101', name: 'คณิต', type: 'core' }, 2: { code: 'ว30101', name: 'ฟิสิกส์', type: 'core' }, 3: { code: 'ว30102', name: 'เคมี', type: 'core' }, 4: { code: 'ท30101', name: 'ไทย', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ก30101', name: 'กิจกรรม', type: 'core' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' } }
        })
    },
    // ม.4 ศิลป์-ภาษา
    'M4-Arts': {
        id: 'M4-Arts', label: 'ม.4 ศิลป์-ภาษา', grade: 4, schedule: createSchedule({
            Monday: { 0: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 1: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 2: { code: 'ท30101', name: 'ไทย', type: 'core' }, 3: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 4: { code: 'ส30101', name: 'สังคม', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'ศ30101', name: 'ศิลปะ', type: 'core' } },
            Tuesday: { 0: { code: 'ส30101', name: 'สังคม', type: 'core' }, 1: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'ท30101', name: 'ไทย', type: 'core' }, 4: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ศ30101', name: 'ศิลปะ', type: 'core' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' } },
            Wednesday: { 0: { code: 'ท30101', name: 'ไทย', type: 'core' }, 1: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 4: { code: 'ส30101', name: 'สังคม', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'ท30101', name: 'ไทย', type: 'core' } },
            Thursday: { 0: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 1: { code: 'ส30101', name: 'สังคม', type: 'core' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 4: { code: 'ท30101', name: 'ไทย', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'พ30101', name: 'พละ', type: 'core' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' } },
            Friday: { 0: { code: 'ท30101', name: 'ไทย', type: 'core' }, 1: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 4: { code: 'ส30101', name: 'สังคม', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ก30101', name: 'กิจกรรม', type: 'core' }, 7: { code: 'ก30101', name: 'กิจกรรม', type: 'core' } }
        })
    },
    // ม.5 วิทย์-คณิต
    'M5-Science': {
        id: 'M5-Science', label: 'ม.5 วิทย์-คณิต', grade: 5, schedule: createSchedule({
            Monday: { 0: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 1: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 2: { code: 'ว30101', name: 'ฟิสิกส์', type: 'core' }, 3: { code: 'ค30101', name: 'คณิต', type: 'core' }, 4: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ว30102', name: 'เคมี', type: 'core' }, 7: { code: 'ท30101', name: 'ไทย', type: 'core' }, 8: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 9: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' } },
            Tuesday: { 0: { code: 'ท30101', name: 'ไทย', type: 'core' }, 1: { code: 'ว30102', name: 'เคมี', type: 'core' }, 2: { code: 'ว30103', name: 'ชีวะ', type: 'core' }, 3: { code: 'ค30101', name: 'คณิต', type: 'core' }, 4: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 7: { code: 'ว30101', name: 'ฟิสิกส์', type: 'core' }, 8: { code: 'ส30101', name: 'สังคม', type: 'core' } },
            Wednesday: { 0: { code: 'ว30101', name: 'ฟิสิกส์', type: 'core' }, 1: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'ว30103', name: 'ชีวะ', type: 'core' }, 4: { code: 'ค30101', name: 'คณิต', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ส30101', name: 'สังคม', type: 'core' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'อ30101', name: 'อังกฤษ', type: 'core' } },
            Thursday: { 0: { code: 'ค30101', name: 'คณิต', type: 'core' }, 1: { code: 'ว30102', name: 'เคมี', type: 'core' }, 2: { code: 'ท30101', name: 'ไทย', type: 'core' }, 3: { code: 'ว30101', name: 'ฟิสิกส์', type: 'core' }, 4: { code: 'ว30103', name: 'ชีวะ', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'พ30101', name: 'พละ', type: 'core' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' } },
            Friday: { 0: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 1: { code: 'ค30101', name: 'คณิต', type: 'core' }, 2: { code: 'ว30101', name: 'ฟิสิกส์', type: 'core' }, 3: { code: 'ว30102', name: 'เคมี', type: 'core' }, 4: { code: 'ท30101', name: 'ไทย', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ก30101', name: 'กิจกรรม', type: 'core' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' } }
        })
    },
    // ม.5 ศิลป์-ภาษา
    'M5-Arts': {
        id: 'M5-Arts', label: 'ม.5 ศิลป์-ภาษา', grade: 5, schedule: createSchedule({
            Monday: { 0: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 1: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 2: { code: 'ท30101', name: 'ไทย', type: 'core' }, 3: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 4: { code: 'ส30101', name: 'สังคม', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'ศ30101', name: 'ศิลปะ', type: 'core' } },
            Tuesday: { 0: { code: 'ส30101', name: 'สังคม', type: 'core' }, 1: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'ท30101', name: 'ไทย', type: 'core' }, 4: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ศ30101', name: 'ศิลปะ', type: 'core' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' } },
            Wednesday: { 0: { code: 'ท30101', name: 'ไทย', type: 'core' }, 1: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 4: { code: 'ส30101', name: 'สังคม', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'ท30101', name: 'ไทย', type: 'core' } },
            Thursday: { 0: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 1: { code: 'ส30101', name: 'สังคม', type: 'core' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 4: { code: 'ท30101', name: 'ไทย', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'พ30101', name: 'พละ', type: 'core' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' } },
            Friday: { 0: { code: 'ท30101', name: 'ไทย', type: 'core' }, 1: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 4: { code: 'ส30101', name: 'สังคม', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ก30101', name: 'กิจกรรม', type: 'core' }, 7: { code: 'ก30101', name: 'กิจกรรม', type: 'core' } }
        })
    },
    // ม.6 วิทย์-คณิต
    'M6-Science': {
        id: 'M6-Science', label: 'ม.6 วิทย์-คณิต', grade: 6, schedule: createSchedule({
            Monday: { 0: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 1: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 2: { code: 'ว30101', name: 'ฟิสิกส์', type: 'core' }, 3: { code: 'ค30101', name: 'คณิต', type: 'core' }, 4: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ว30102', name: 'เคมี', type: 'core' }, 7: { code: 'ท30101', name: 'ไทย', type: 'core' }, 8: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 9: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' } },
            Tuesday: { 0: { code: 'ท30101', name: 'ไทย', type: 'core' }, 1: { code: 'ว30102', name: 'เคมี', type: 'core' }, 2: { code: 'ว30103', name: 'ชีวะ', type: 'core' }, 3: { code: 'ค30101', name: 'คณิต', type: 'core' }, 4: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 7: { code: 'ว30101', name: 'ฟิสิกส์', type: 'core' }, 8: { code: 'ส30101', name: 'สังคม', type: 'core' } },
            Wednesday: { 0: { code: 'ว30101', name: 'ฟิสิกส์', type: 'core' }, 1: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'ว30103', name: 'ชีวะ', type: 'core' }, 4: { code: 'ค30101', name: 'คณิต', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ส30101', name: 'สังคม', type: 'core' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'อ30101', name: 'อังกฤษ', type: 'core' } },
            Thursday: { 0: { code: 'ค30101', name: 'คณิต', type: 'core' }, 1: { code: 'ว30102', name: 'เคมี', type: 'core' }, 2: { code: 'ท30101', name: 'ไทย', type: 'core' }, 3: { code: 'ว30101', name: 'ฟิสิกส์', type: 'core' }, 4: { code: 'ว30103', name: 'ชีวะ', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'พ30101', name: 'พละ', type: 'core' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' } },
            Friday: { 0: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 1: { code: 'ค30101', name: 'คณิต', type: 'core' }, 2: { code: 'ว30101', name: 'ฟิสิกส์', type: 'core' }, 3: { code: 'ว30102', name: 'เคมี', type: 'core' }, 4: { code: 'ท30101', name: 'ไทย', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ก30101', name: 'กิจกรรม', type: 'core' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' } }
        })
    },
    // ม.6 ศิลป์-ภาษา
    'M6-Arts': {
        id: 'M6-Arts', label: 'ม.6 ศิลป์-ภาษา', grade: 6, schedule: createSchedule({
            Monday: { 0: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 1: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 2: { code: 'ท30101', name: 'ไทย', type: 'core' }, 3: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 4: { code: 'ส30101', name: 'สังคม', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'ศ30101', name: 'ศิลปะ', type: 'core' } },
            Tuesday: { 0: { code: 'ส30101', name: 'สังคม', type: 'core' }, 1: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'ท30101', name: 'ไทย', type: 'core' }, 4: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ศ30101', name: 'ศิลปะ', type: 'core' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' } },
            Wednesday: { 0: { code: 'ท30101', name: 'ไทย', type: 'core' }, 1: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 4: { code: 'ส30101', name: 'สังคม', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'ท30101', name: 'ไทย', type: 'core' } },
            Thursday: { 0: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 1: { code: 'ส30101', name: 'สังคม', type: 'core' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 4: { code: 'ท30101', name: 'ไทย', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'พ30101', name: 'พละ', type: 'core' }, 7: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 8: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' } },
            Friday: { 0: { code: 'ท30101', name: 'ไทย', type: 'core' }, 1: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 2: { code: 'ELECTIVE', name: 'วิชาเลือก', type: 'elective' }, 3: { code: 'อ30101', name: 'อังกฤษ', type: 'core' }, 4: { code: 'ส30101', name: 'สังคม', type: 'core' }, 5: { code: '', name: 'พักเที่ยง', type: 'break' }, 6: { code: 'ก30101', name: 'กิจกรรม', type: 'core' }, 7: { code: 'ก30101', name: 'กิจกรรม', type: 'core' } }
        })
    },
};

export const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];
export const DAY_NAMES_TH: Record<string, string> = {
    Monday: 'จันทร์',
    Tuesday: 'อังคาร',
    Wednesday: 'พุธ',
    Thursday: 'พฤหัสบดี',
    Friday: 'ศุกร์'
};
export const PERIODS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
